version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'Jakarta456!'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
